# site description
description = "Stime's Blog"
# site keywords
keywords = ["Stimw", "Site", "Blog"]
# LoveIt theme version
version = "0.2.X"

[search]
  enable = false
  # type of search engine ("lunr", "algolia", "fuse")
  type = "fuse"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = ""
  # DoIt NEW | 0.2.1 max number of results length
  maxResultLength = 10
  # DoIt NEW | 0.2.3 snippet length of the result
  snippetLength = 30
  # DoIt NEW | 0.2.1 HTML tag name of the highlight part in results
  highlightTag = "em"
  # DoIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
  absoluteURL = false
  [search.fuse]
    # DoIt NEW | 0.2.12 https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.3
    distance = 100
    ignoreLocation = false
    useExtendedSearch = false
    ignoreFieldNorm = false

# Header config
[header]
  # desktop header mode ("fixed", "normal", "auto")
  desktopMode = "fixed"
  # mobile header mode ("fixed", "normal", "auto")
  mobileMode = "auto"
# LoveIt NEW | 0.2.0 Header title config
# [header.title]
#   # URL of the LOGO
#   logo = ""
#   # title name
#   name = ""
#   # you can add extra information before the name (HTML format is supported), such as icons
#   pre = ""
#   # you can add extra information after the name (HTML format is supported), such as icons
#   post = ""
# # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
# typeit = false
  
# Footer config
[footer]
  enable = true
  # LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
  custom = ''
  # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
  hugo = false
  # LoveIt NEW | 0.2.0 whether to show copyright info
  copyright = true
  # LoveIt NEW | 0.2.0 whether to show the author
  author = true
  # Site creation time
  since = 2022
  # ICP info only in China (HTML format is supported)
  license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# LoveIt NEW | 0.2.0 Section (all posts) page config
[section]
  # special amount of posts in each section page
  paginate = 20
  # date format (month and day)
  dateFormat = "01-02"
  # amount of RSS pages
  rss = 10

# LoveIt NEW | 0.2.0 List (category or tag) page config
[list]
  # special amount of posts in each list page
  paginate = 20
  # date format (month and day)
  dateFormat = "01-02"
  # amount of RSS pages
  rss = 10

# Home page config
[home]
  # LoveIt NEW | 0.2.0 amount of RSS pages
  rss = 10
  # Home page profile
  [home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = ""
    # URL of avatar shown in home page
    avatarURL = "/images/avatar.png"
    # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
    title = ""
    # subtitle shown in home page
    subtitle = "A guy who's not good at blogging"
    # whether to use typeit animation for subtitle
    typeit = true
    # whether to show social links
    social = true
    # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
    disclaimer = ""
  # Home page posts
  [home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 6
    # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in page
    # default behavior when you don't set "hiddenFromHomePage" in front matter
    defaultHiddenFromHomePage = false

# Social config about the author
[social]
  GitHub = "stimw"
  Linkedin = ""
  Twitter = ""
  Instagram = ""
  Facebook = ""
  Telegram = ""
  Email = "stimwblog@gmail.com"
  RSS = true # LoveIt NEW | 0.2.0
  
# DoIt CHANGED | 0.2.0 Page config
[page]
  # DoIt NEW | 0.2.0 whether to hide a page from home page
  hiddenFromHomePage = false
  # DoIt NEW | 0.2.0 whether to hide a page from search results
  hiddenFromSearch = false
  # DoIt NEW | 0.2.0 whether to enable twemoji
  twemoji = false
  # whether to enable lightgallery
  lightgallery = false
  # DoIt NEW | 0.2.0 whether to enable the ruby extended syntax
  ruby = true
  # DoIt NEW | 0.2.0 whether to enable the fraction extended syntax
  fraction = true
  # DoIt NEW | 0.2.0 whether to enable the fontawesome extended syntax
  fontawesome = true
  # whether to show link to Raw Markdown content of the content
  linkToMarkdown = true
  # DoIt NEW | 0.2.14 configure the link to the source file of the post
  linkToSource = false
  # "https://github.com/user/repo/blob/main/{path}"
  # DoIt NEW | 0.2.13 configure the link to edit the post
  linkToEdit = false
  # "https://github.com/user/repo/edit/main/{path}"
  # "https://gitlab.com/user/repo/-/edit/main/{path}"
  # "https://bitbucket.org/user/repo/src/main/{path}?mode=edit"
  # DoIt NEW | 0.2.14 configure the link to report issue for the post
  linkToReport = false
  # "https://github.com/user/repo/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/user/repo/blob/main/{path}|"
  # DoIt NEW | 0.2.4 whether to show the full text content in RSS
  rssFullText = false
  # DoIt NEW | 0.2.11 page layout style ("normal", "wide")
  pageStyle = "normal"
  # DoIt NEW | 0.2.13 whether to enable series navigation
  seriesNavigation = true
  # DoIt NEW | 0.2.13 outdated article reminder config
  [page.outdatedArticleReminder]
    enable = false
    # Display the reminder if the last modified time is more than 90 days ago.
    reminder = 90
    # Display warning if the last modified time is more than 180 days ago.
    warning = 180
  # DoIt NEW | 0.2.0 Table of the contents config
  [page.toc]
    # whether to enable the table of the contents
    enable = true
    # DoIt NEW | 0.2.9 whether to keep the static table of the contents in front of the post
    keepStatic = false
    # whether to make the table of the contents in the sidebar automatically collapsed
    auto = true
  # DoIt CHANGED | 0.2.0 KaTeX mathematical formulas
  [page.math]
    enable = true
    # default block delimiter is $$ ... $$ and \\[ ... \\]
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # default inline delimiter is $ ... $ and \\( ... \\)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # KaTeX extension copy_tex
    copyTex = true
    # KaTeX extension mhchem
    mhchem = true
  # DoIt NEW | 0.2.0 Code config
  [page.code]
    # whether to show the copy button of the code block
    copy = true
    # the maximum number of lines of displayed code by default
    maxShownLines = 10
  # DoIt NEW | 0.2.14 Table config
  # [page.table]
  #   # whether to enable sorting in the tables
  #   sort = true
  # DoIt NEW | 0.2.0 Mapbox GL JS config
  [page.mapbox]
    # access token of Mapbox GL JS
    accessToken = ""
    # style for the light theme
    lightStyle = "mapbox://styles/mapbox/light-v9"
    # style for the dark theme
    darkStyle = "mapbox://styles/mapbox/dark-v9"
    # whether to add NavigationControl
    navigation = true
    # whether to add GeolocateControl
    geolocate = true
    # whether to add ScaleControl
    scale = true
    # whether to add FullscreenControl
    fullscreen = true
  # DoIt CHANGED | 0.2.0 social share links in post page
  [page.share]
    enable = true
    Twitter = true
    Facebook = true
    Linkedin = false
    Whatsapp = true
    HackerNews = true
    Reddit = true
    Line = true

  [page.comment]
    enable = true
    [page.comment.waline]
        # DoIt CHANGED | 0.2.13
        enable = true
        serverURL = "https://waline-blog-e4ul75i2d-stimw.vercel.app/"
        visitor = false
        emoji = ['https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/weibo']
        meta = ['nick', 'mail', 'link']
        requiredMeta = ['nick', 'mail']
        login = 'disable'
        wordLimit = 0
        pageSize = 10
        imageUploader = false
        highlighter = false
        texRenderer = false

