# site description
description = "Stime's Blog"
# site keywords
keywords = ["Stimw", "Site", "Blog"]
# LoveIt theme version
version = "0.2.X"

# Header config
[header]
  # desktop header mode ("fixed", "normal", "auto")
  desktopMode = "fixed"
  # mobile header mode ("fixed", "normal", "auto")
  mobileMode = "auto"
# LoveIt NEW | 0.2.0 Header title config
# [header.title]
#   # URL of the LOGO
#   logo = ""
#   # title name
#   name = ""
#   # you can add extra information before the name (HTML format is supported), such as icons
#   pre = ""
#   # you can add extra information after the name (HTML format is supported), such as icons
#   post = ""
# # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
# typeit = false
  
# Footer config
[footer]
  enable = true
  # LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
  custom = ''
  # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
  hugo = false
  # LoveIt NEW | 0.2.0 whether to show copyright info
  copyright = true
  # LoveIt NEW | 0.2.0 whether to show the author
  author = true
  # Site creation time
  since = 2022
  # ICP info only in China (HTML format is supported)
  icp = ""
  # license info (HTML format is supported)
  license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# LoveIt NEW | 0.2.0 Section (all posts) page config
[section]
  # special amount of posts in each section page
  paginate = 20
  # date format (month and day)
  dateFormat = "01-02"
  # amount of RSS pages
  rss = 10

# LoveIt NEW | 0.2.0 List (category or tag) page config
[list]
  # special amount of posts in each list page
  paginate = 20
  # date format (month and day)
  dateFormat = "01-02"
  # amount of RSS pages
  rss = 10

# Home page config
[home]
  # LoveIt NEW | 0.2.0 amount of RSS pages
  rss = 10
  # Home page profile
  [home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = ""
    # URL of avatar shown in home page
    avatarURL = "/images/avatar.png"
    # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
    title = ""
    # subtitle shown in home page
    subtitle = "A guy who's not good at blogging"
    # whether to use typeit animation for subtitle
    typeit = true
    # whether to show social links
    social = true
    # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
    disclaimer = ""
  # Home page posts
  [home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 6
    # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
    # default behavior when you don't set "hiddenFromHomePage" in front matter
    defaultHiddenFromHomePage = false

# Social config about the author
[social]
  GitHub = "stimw"
  Linkedin = ""
  Twitter = ""
  Instagram = ""
  Facebook = ""
  Telegram = ""
  Email = "stimwblog@gmail.com"
  RSS = true # LoveIt NEW | 0.2.0